Goalzones implementation
SW805F20/Unity pull request #11
Opened 2020-03-03 08:22 UTC by Eduardsen

2020-03-18 10:12 UTC, Tekrus requested changes

2020-03-18 10:12 UTC, Moesgaarda commented on TeamBuildingGame/ProjectSettings/ProjectVersion.txt
> +m_EditorVersion: 2019.3.2f1
```suggestion
m_EditorVersion: 2019.3.1f1
```

2020-03-20 08:48 UTC, Tekrus requested changes
Generelt: Overvej Vector2 i stedet for Vector3.

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +        Horizontal
Er det length?

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +    float[] xSizeArray, ySizeArray;
Generelt: Skriv nogle kommentarer med hvad variable bruges til, det er ikke just selvsigende

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +    public Vector3 fieldAnchor1, fieldAnchor2, fieldAnchor3, fieldAnchor4;
Kan de her ikke være vector 2?

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +        }
Kan den ikke komme til at køre den her flere gange, hvis GenerateNewGoalZones() ikke er færdig med at køre inden næste frame?

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +                SpawnMirroringGoals(randomXBlue, randomYBlue);
Du kalder metoden flere gange med samme parametre, kan den ikke flyttes udenfor if-else?

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +        anchorArray[3] = new Vector3(midPointForGoal.x + goalZoneMiddleOffset, midPointForGoal.y + goalZoneMiddleOffset, 1f);
Kan det ikke være vector2?

2020-03-20 08:48 UTC, Moesgaarda commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +        Vector3[] anchors;
Vector2?

2020-03-20 09:01 UTC, Eduardsen commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +        Horizontal
det er om en akse er længere end den anden, hvis x aksen er længst er spillebanet horizontal, ellers vertikal

2020-03-20 09:05 UTC, Eduardsen commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +    public Vector3 fieldAnchor1, fieldAnchor2, fieldAnchor3, fieldAnchor4;
det er dem fra playingfield, og de er vector3 pga de er meshes

2020-03-20 09:08 UTC, Eduardsen commented on TeamBuildingGame/Assets/Scripts/PlayingArea/GoalZoneController.cs
> +        }
Måske 🤔 tilføjede at den sætter goalscored til false med det samme før den kalder fucnktionen, så det burde ikke være et problem nu

2020-03-20 09:20 UTC, Tekrus approved these changes

2020-03-20 09:21 UTC, Tekrus approved these changes

2020-03-20 09:21 UTC, MathiasLybech approved these changes

2020-03-20 09:21 UTC, merged