PROJ-17 C# udpclient
SW805F20/Unity pull request #12
Opened 2020-03-06 10:13 UTC by Eduardsen

2020-03-06 10:24 UTC, Fatdet requested changes

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +public class UDPClient : MonoBehaviour
Du følger ikke dokumentation guiden

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +            Debug.Log(e.Message);
MÅ VI GERNE HAVE CONSOLE PRINTS???? måske lav en logger fil til exceptions

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +            uClient.BeginReceive(new AsyncCallback(Receive), null);
forklar hvad null gør, hvorfor skal det sendes med?

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        IPEndPoint RemoteIpEndPoint = new IPEndPoint(IPAddress.Any, 0);
0 burde være en variabel

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +            Debug.Log("This is the message you received " +
igen flere logs

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        catch (Exception e)
e er et intet sigende navn imo

2020-03-06 10:24 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        catch (Exception e)
e er et intet sigende navn imo

2020-03-06 10:42 UTC, jenspetur94 requested changes

2020-03-06 10:42 UTC, jenspetur94 commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        //Establiehs a udp connection on the port.
```suggestion
        //Establishes a UDP connection on the port.
```

2020-03-06 10:53 UTC, Fatdet requested changes

2020-03-06 10:53 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +﻿using System.Collections;
ikke brugte usings

2020-03-06 11:10 UTC, Fatdet requested changes

2020-03-06 11:10 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        //Establishes a udp connection on the port.
der skal være mellemrum mellem // og kommentaren

2020-03-06 11:10 UTC, Fatdet commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        //Establishes a udp connection on the port.
gælder også andre kommentarer

2020-03-06 11:20 UTC, Eduardsen commented on TeamBuildingGame/Assets/Scripts/udpclient/UDPClient.cs
> +        //Establishes a udp connection on the port.
Lav det som suggestions hvis det er vigtigt 💯

2020-03-12 14:13 UTC, jenspetur94 approved these changes

2020-03-12 14:46 UTC, Fatdet approved these changes

2020-03-13 08:31 UTC, merged