Connection menu
SW805F20/Unity pull request #33
Opened 2020-04-30 09:16 UTC by Moesgaarda

2020-04-30 12:04 UTC, andpaacoke commented on TeamBuildingGame/Assets/Scripts/tcpclient/TCPClient.cs
>          {
Her skal man nok smides tilbage til connect start menuen da den fejlede i at connecte og skal have muligheden for at indtaste en ny IP. Måske skal der også være en fejlbesked på startmenuen der fortæller at den fejlede i at connecte

2020-04-30 12:06 UTC, andpaacoke requested changes
Der mangler noget errorhandling. Ved heller ikke om CLIENT gameobject måske skal ligge i startmenuen og føres videre med over i næste scene så man ikke behøver skifte scene før den har lavet en succesfuld connection

2020-05-01 07:22 UTC, andpaacoke approved these changes

2020-05-01 07:23 UTC, MathiasLybech approved these changes

2020-05-01 07:29 UTC, merged